feign:
  sentinel:
    enabled: true
spring:
  datasource:
    url: jdbc:mysql://192.168.100.100:3306/ts_bank1_xa?characterEncoding=UTF-8&serverTimezone=CTT&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=true
    username: root
    password: 123456
    hikari:
      ## 最小空闲连接数量
      minimum-idle: 3
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 15
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 600000
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      ##检查connection是否可用的语句
      connection-init-sql: SELECT 1
  redis:
    port: 6379
    #本机服务器
    host: 192.168.100.100
    password:
    timeout: 10000
    database: 0
    lettuce:
      pool:
        max-active: 200
        max-wait: -1
        min-idle: 0
        max-idle: 10